package try_catch_test;

public class DogException3 extends Exception {

	public DogException3() {
		// TODO 自動產生的建構子 Stub
	}

	public DogException3(String message) {
		super(message);
		// TODO 自動產生的建構子 Stub
	}

	public DogException3(Throwable cause) {
		super(cause);
		// TODO 自動產生的建構子 Stub
	}

	public DogException3(String message, Throwable cause) {
		super(message, cause);
		// TODO 自動產生的建構子 Stub
	}

	public DogException3(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
		// TODO 自動產生的建構子 Stub
	}

}
